import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { courses } from '@/lib/courses/registry';
import { slugifyHungarian } from '@/lib/audio-slug';

type AudioPhrase = { id: string; hungarian: string };

function getUniqueHungarianPhrases(): string[] {
	const phrases = new Set<string>();

	for (const course of courses) {
		for (const lesson of course.lessons) {
			for (const entry of lesson.entries) {
				phrases.add(entry.hungarian);
			}
		}
	}

	return [...phrases].sort((a, b) => a.localeCompare(b, 'hu'));
}

function buildCatalog(): AudioPhrase[] {
	const slugCounts = new Map<string, number>();
	const catalog: AudioPhrase[] = [];

	for (const hungarian of getUniqueHungarianPhrases()) {
		const base = slugifyHungarian(hungarian) || 'phrase';
		const count = slugCounts.get(base) ?? 0;
		slugCounts.set(base, count + 1);
		const id = count === 0 ? base : `${base}-${count + 1}`;
		catalog.push({ id, hungarian });
	}

	return catalog;
}

function escapeString(value: string): string {
	return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function formatCatalog(catalog: AudioPhrase[]): string {
	const rows = catalog
		.map((phrase) => `\t{ id: '${escapeString(phrase.id)}', hungarian: '${escapeString(phrase.hungarian)}' },`)
		.join('\n');

	return `// Generated by scripts/build-audio-catalog.ts — do not edit by hand.
// Re-run: npm run build:audio-catalog

export type AudioPhrase = {
	id: string;
	hungarian: string;
};

export const AUDIO_PHRASES = [
${rows}
] as const satisfies readonly AudioPhrase[];

export type AudioPhraseId = (typeof AUDIO_PHRASES)[number]['id'];

const hungarianToAudioId = new Map<string, AudioPhraseId>(
	AUDIO_PHRASES.map((phrase) => [phrase.hungarian, phrase.id]),
);

export function getAudioId(hungarian: string): AudioPhraseId {
	const id = hungarianToAudioId.get(hungarian);
	if (!id) {
		throw new Error(\`No audio ID for Hungarian phrase: \${hungarian}\`);
	}
	return id;
}
`;
}

const catalog = buildCatalog();
const outputPath = join(process.cwd(), 'src/lib/audio-catalog.ts');
writeFileSync(outputPath, formatCatalog(catalog));
console.log(`Wrote ${catalog.length} phrases to ${outputPath}`);
